from pydantic import BaseModel, Field

class Rating(BaseModel):
    id : str
    isbn : str
    rating : int = Field(min_length=1, max_length=5)
    
class RatingCreate(BaseModel):
    id : str # probably dont have this, id shiuld be generated by the service and dont automatically, similar to your user schema
    isbn : str
    rating : str
    
class RatingUpdate(BaseModel):
    rating : str